### ISSUE TITLE
SyntaxError: f-string: unmatched '['

### ISSUE THREAD

**Issue by aj-naqib** [MananSoni42/lmdocs#1]
First time using the tool, ran into issue trying to read f strings. 

```
2024-06-27 20:47:40 INFO     Project path: /home/aj/workspace/alias-scout/alias_scout
2024-06-27 20:47:40 INFO     Using openai LLM: gpt-3.5-turbo
2024-06-27 20:47:40 INFO     Extracting dependancies from /home/aj/workspace/alias-scout/alias_scout/utils.py
2024-06-27 20:47:40 INFO     Extracting dependancies from /home/aj/workspace/alias-scout/alias_scout/local_handler.py
2024-06-27 20:47:40 INFO     Extracting dependancies from /home/aj/workspace/alias-scout/alias_scout/main.py
Traceback (most recent call last):
  File "/home/aj/workspace/temp/lmdocs/lmdocs.py", line 54, in <module>
    main()
  File "/home/aj/workspace/temp/lmdocs/lmdocs.py", line 27, in main
    code_dependancies, import_stmts = get_code_dependancies_and_imports(args.path)
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aj/workspace/temp/lmdocs/utils.py", line 135, in get_code_dependancies_and_imports
    import_stmts.extend(get_all_imports(code_str)[2])
                        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aj/workspace/temp/lmdocs/python_parsers.py", line 102, in get_all_imports
    tree = ast.parse(code_str)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/aj/.pyenv/versions/3.11.9/lib/python3.11/ast.py", line 50, in parse
    return compile(source, filename, mode, flags,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<unknown>", line 27
    logger.info(f"Running task: {event["taskId"]}")
                                        ^^^^^^
SyntaxError: f-string: unmatched '['

**Comment by MananSoni42** [comment]
Hi @aj-naqib,
This seems like an error in your code instead of in the tool.

The error is caused by the line:
f"Running task: {event["taskId"]}"

You can fix it by using this line instead:
f"Running task: {event['taskId']}"

Notice the different quotes that I have used. Let me know if youface any other isssues while using the tool :)

**Comment by aj-naqib** [comment]
Yeah, I read the ast docs and refactored my code- and so far, I'm still making inferences. It's a large project so `Generating docs for 200 custom functions/methods/classes` 

Excited to see what the results look like.
