### ISSUE TITLE
import _distutils_hack.override  # noqa: F401 - issue on mac 3.11

### ISSUE THREAD

**Issue by dakoller** [MananSoni42/lmdocs#4]
I installed lmdocs in an own directory (no virtual env) on Max with python 3.11. Any idea how to fix this?

`Traceback (most recent call last):
  File "/Users/dakoller/projects/lmdocs/lmdocs.py", line 74, in <module>
    main()
  File "/Users/dakoller/projects/lmdocs/lmdocs.py", line 46, in main
    reference_docs = get_reference_docs_simple_functions(import_stmts, simple_funcs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dakoller/projects/lmdocs/get_code_docs.py", line 263, in get_reference_docs_simple_functions
    exec(stmt)
  File "<string>", line 1, in <module>
  File "/Users/dakoller/anaconda3/lib/python3.11/site-packages/setuptools/__init__.py", line 7, in <module>
    import _distutils_hack.override  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dakoller/anaconda3/lib/python3.11/site-packages/_distutils_hack/override.py", line 1, in <module>
    __import__('_distutils_hack').do_override()
  File "/Users/dakoller/anaconda3/lib/python3.11/site-packages/_distutils_hack/__init__.py", line 77, in do_override
    ensure_local_distutils()
  File "/Users/dakoller/anaconda3/lib/python3.11/site-packages/_distutils_hack/__init__.py", line 64, in ensure_local_distutils
    assert '_distutils' in core.__file__, core.__file__
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: /Users/dakoller/anaconda3/lib/python3.11/distutils/core.py`

**Comment by MananSoni42** [comment]
Hi @dakoller,
This does not seem like an issue with lmdocs,
Given the trace, I suspect it is something wrong with your python setup, can you try by upgrading the setuptools module 
Reference: https://stackoverflow.com/questions/71027006/assertionerror-inside-of-ensure-local-distutils-when-building-a-pyinstaller-exe

**Comment by MananSoni42** [comment]
Is there any extended trace available?
That can help narrow it down as well

**Comment by dakoller** [comment]
downgrading at least helped me further:

pip install setuptools==59.8.0
